export {
  connectJmap,
  deleteEmails,
  getEmailChanges,
  getEmails,
  getMailboxes,
  getSearchUpdates,
  getThreads,
  markEmails,
  moveEmails,
  patchEmailMailboxes,
  replyToEmail,
  searchEmails,
  sendEmail,
} from "./src/client.ts";

export type {
  AddedEmail,
  DeleteEmailsInput,
  DeleteEmailsResult,
  Email,
  EmailAddress,
  GetEmailChangesInput,
  GetEmailChangesResult,
  GetEmailsInput,
  GetEmailsResult,
  GetMailboxesInput,
  GetMailboxesResult,
  GetSearchUpdatesInput,
  GetSearchUpdatesResult,
  GetThreadsInput,
  GetThreadsResult,
  JmapConnection,
  JmapConnectionConfig,
  Mailbox,
  MarkEmailsInput,
  MoveEmailsInput,
  PatchEmailMailboxesInput,
  ReplyToEmailInput,
  ReplyToEmailResult,
  SearchEmailsInput,
  SearchEmailsResult,
  SendEmailInput,
  SendEmailResult,
  Thread,
  UpdateEmailsResult,
} from "./src/client.ts";
export type { EmailFilterCondition } from "jmap-rfc-types";
